#! /bin/bash
# Wrapper script for launching the AIA command line tool in POSIX environments

if ! command -v java >/dev/null 2>&1; then
  echo "ERROR - The java command was not found."
  echo "Ensure that you have installed the Java Runtime Environment, and"
  echo "that its location has been added to your PATH."
  exit 1
fi

scriptdir="$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )"

java -jar "$scriptdir/aia.jar" -w "$(tput cols)" "$@"
