# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

submit_for_review true
force true
skip_screenshots true
skip_metadata true

for_platform :mac do
  platform "osx"
  pkg "Card Game Simulator.pkg"
end
