# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

submit_for_review true
force true
skip_screenshots true
release_notes({
  'default' => "- Removed splash screen to speed up startup\n- Fixed: Hold Card to Zoom",
  'en-US' => "- Removed splash screen to speed up startup\n- Fixed: Hold Card to Zoom"
})
run_precheck_before_submit false

for_platform :mac do
  platform "osx"
  pkg "Card Game Simulator.pkg"
end
