# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

submit_for_review true
automatic_release true
force true
skip_screenshots true
release_notes({
  'default' => ENV["RELEASE_NOTES"],
  'en-US' => ENV["RELEASE_NOTES"]
})
run_precheck_before_submit false

submission_information({
  add_id_info_uses_idfa: false,
  export_compliance_compliance_required: false,
  export_compliance_encryption_updated: false,
  export_compliance_app_type: nil,
  export_compliance_uses_encryption: false,
  export_compliance_is_exempt: false,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_contains_proprietary_cryptography: false,
  export_compliance_available_on_french_store: false
})

app_store_connect_api_key(
  key_id: "#{ENV['APPSTORE_KEY_ID']}",
  issuer_id: "#{ENV['APPSTORE_ISSUER_ID']}",
  key_filepath: "#{ENV['APPSTORE_P8_PATH']}",
  duration: 1200, # optional
  in_house: false, # true for enterprise and false for individual accounts
)

for_platform :mac do
  platform "osx"
  pkg "#{ENV['PROJECT_NAME']}.pkg"
end
