plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: Card Game Simulator
description: Create, Share, and Play card games with Card Game Simulator
url: 'https://www.cardgamesimulator.com'
lang: en-US
logo: /assets/img/CGSLogo.png
image: https://www.cardgamesimulator.com/assets/img/CGSLogo.png
social:
  name: Card Game Simulator
  links:
    - https://github.com/finol-digital/Card-Game-Simulator
    - https://bsky.app/profile/cardgamesim.bsky.social
theme: jekyll-theme-slate
