name: Release Announcement
on: workflow_dispatch
jobs:
  announceReleaseToSocialMedia:
    name: Announce Release to Social Media
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Version
        id: versioning
        uses: paulhatch/semantic-version@v5.4.0
        with:
          version_format: "${major}.${minor}"
          minor_pattern: "(MINOR)"
          bump_each_commit: false
          debug: true
      - name: Prepare Announcement
        id: prepare
        shell: bash
        env:
          VERSION: v${{ steps.versioning.outputs.version }}
        run: |
          RELEASE_NOTES="$(cat fastlane/metadata/en-US/release_notes.txt)"
          export ANNOUNCEMENT="Released CGS $VERSION! $RELEASE_NOTES"
          echo "$ANNOUNCEMENT"
          echo 'ANNOUNCEMENT<<EOF' >> $GITHUB_OUTPUT
          echo "$ANNOUNCEMENT" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Discord Announcement
        if: github.ref == 'refs/heads/main'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ steps.prepare.outputs.ANNOUNCEMENT }}
